# Generated by Django 4.0.3 on 2022-03-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="foto",
            field=models.TextField(),
        ),
    ]
